version: "3"

services:
  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.92.0
    volumes:
      - ./otel-collector-config.yaml:/etc/otelcol-contrib/config.yaml
    ports:
      - "13133:13133" # OTLP Health Check
      - "4317:4317" # OTLP gRPC receiver
      - "4318:4318" # OTLP http receiver
    env_file:
      - ".env"

