FROM python:3.8-slim-buster

ENV PYTHONUNBUFFERED 1
ENV DJANGO_SETTINGS_MODULE pokeservice.settings
ENV PYTHONPATH=/srv/app/

WORKDIR /srv/app/

RUN apt-get update -y && \
    apt-get install -y -- build-essential \
    default-libmysqlclient-dev \
    gettext libpq-dev


COPY requirements/django.txt  .

RUN pip install --no-cache-dir -r django.txt

COPY backends/pokeservice .

HEALTHCHECK --interval=5m --timeout=3s \
  CMD curl -f http://localhost:8000/ht/ || exit 1

