receivers:
  otlp:
    protocols:
      http:
        endpoint: ${HTTP_RECEIVER_ENDPOINT} # HTTP receiver endpoint inside collector service
      grpc:
        endpoint: ${GRPC_RECEIVER_ENDPOINT} # grpc receiver inside collector service

  # Internal collector processor configuration.

processors:
  batch:
    send_batch_max_size: 100
    send_batch_size: 10
    timeout: 10s

  # Internal collector exporters debug to see incoming data in collector console and datadog to send data to datadog service.

exporters:
  debug:
    verbosity: detailed
  datadog:
    api:
      site: ${DATADOG_SITE}
      key: ${DATADOG_API_KEY}
  sentry:
    dsn: ${SENTRY_DNS}



  # Service pipelines configuration in order to receive, process and export data to backends services.

service:
  pipelines:
    metrics:
      receivers: [otlp]
      exporters: [debug, datadog ]
      processors: [batch]
    traces:
      receivers: [otlp]
      exporters: [debug, datadog, sentry]
      processors: [batch]
    logs:
      receivers: [otlp]
      exporters: [debug, datadog ]
      processors: [batch]
