# Generated by Django 3.2.23 on 2024-01-18 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='data',
            field=models.JSONField(default={}),
            preserve_default=False,
        ),
    ]
