# Generated by Django 3.2.23 on 2024-01-18 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0002_pokemon_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pokemon',
            name='data',
        ),
        migrations.AddField(
            model_name='pokemon',
            name='height',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pokemon',
            name='sprite',
            field=models.URLField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='pokemon',
            name='weight',
            field=models.IntegerField(default=0),
        ),
    ]
